### PR TITLE
almost all fixed

### PR DESCRIPTION
**Pull request by doutriaux1**
@jccosta  the newest vcs seems to have broken your EzPlot, beause

- we fixed the defaut size of symbols to make them unfiorm, you probably want to tweak your default
- EzPlot_test1 the legend is now broken, not all "cos" appear

### CODE REVIEW

**Comment by doutriaux1** [comment]
@jccosta meant to tag you!

**Comment by doutriaux1** [comment]
@jpocom any update on this?

**Comment by jccosta** [comment]
@doutriaux1 I didn't have time to look at it this week. Sorry for that. I will fix it first thing on Monday.

**Comment by doutriaux1** [comment]
thanks for this. it is (in part) holding back @muryanto1 nightly test suite work.

**Pull request merged**
