### PR TITLE
Improve level spacing for polaroned

### PR DESCRIPTION
**Pull request by chaosphere2112**
Previously, levels were distributed from min to max using linear spacing.

```
import vcs
import vcsaddons
import math

polar = vcsaddons.createpolar()
polar.magnitude_ticks = [1, 10, 100]
polar.magnitude_tick_angle = math.pi / 8
polar.markersizes = [2]

values = [1, 5, 10, 50, 100]
angles = [i *  (2 * math.pi/len(values)) for i in range(len(values))]

x = vcs.init()
x = polar.plot(values, angles, x=x)
x.png("polar_levels")
```

generates this image on master:

polar_levels

In order to make things like log scale possible (and to be able to extract some detail from very tight distributions with huge outliers), I've changed it so the levels as given will be evenly distributed across the plot, and interpolating between two levels will be done on a linear scale (which is a little weird, but the best that I could come up with). The earlier script will now give this plot:

polar_levels

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chaosphere2112 can we control the behaviour? The new one should be the default, but I'm sure we will run eventually into a user expecting/wanting the other way.

**Comment by doutriaux1** [comment]
also can you pass a 2D array instead of value/angle, that would make it consistent with taylordiagrams

**Comment by chaosphere2112** [comment]
@doutriaux1 Already can pass a 2D array, yes. I wrote a rather complicated input validation function that will handle most reasonable permutations of sending in data.

**Comment by chaosphere2112** [comment]
@doutriaux1 As discussed in person, the old behavior can be replicated by creating the scale that you're actually looking for and then hiding tick marks (though an example of that would probably be good).

**Comment by doutriaux1** [comment]
@chaosphere2112 I'm not positive that would do the trick, look at the points near "10" they are not at the same location between the plots.

**Comment by chaosphere2112** [comment]
@doutriaux1 I'll come up with an example of how to do it on Monday

**Comment by chaosphere2112** [comment]
@doutriaux1 ...or maybe tuesday

**Comment by doutriaux1** [comment]
@chaosphere2112 what was this about again? Do we want it?

**Comment by chaosphere2112** [comment]
@doutriaux1 This PR makes the space between magnitude ticks be even. The old behavior interpolated the distance from the min to the max, and placed the ticks at a distances from the center corresponding to their percentage of the difference between min and max. This allows for log scales, and I think some other stuff like an inverted scale (max in the center, min at these outside).

**Pull request merged**
